### ISSUE TITLE
README refers to non-existent dns_stub_resolver parameter

### ISSUE THREAD

**Issue by anarcat** [voxpupuli/puppet-systemd#195]
The README currently says:

> When configuring `systemd::resolved` you could set `dns_stub_resolver` to `false` (default) to use a standard /etc/resolved.conf, or you could set it to `true` to use the local resolver provided by `systemd-resolved`.

But the `dns_stub_resolver` parameter doesn't exist anywhere. There are `dns_stub_listener` and `use_stub_resolver` in `systemd::resolved` but neither do what is described above (which is, i guess, to leave resolv.conf alone?)

Anyways, this is rather all unclear and i suspect it should instead document whatever it is that `use_stub_resolver` does, but even that is not quite clear to me. :)

**Comment by simondeziel** [comment]
This was fixed by commit f71a4ad4673e5f6d241
