### ISSUE TITLE
Mark camptocamp module as deprecated

### ISSUE THREAD

**Issue by timdeluxe** [voxpupuli/puppet-systemd#211]
Please mark the old camptocamp module as deprecated, so that people (and API using programs) see the transfer to the new author.

**Comment by smortex** [comment]
Cc @raphink @mcanevet 

According to [this documentation](https://forgeapi.puppet.com/#operation/deprecateModule), an API call with a valid bearer token should do it (never tried this!):

```
curl -X PATCH -H 'Content-Type: application/json' -H 'Authorization: Bearer 1234' https://forgeapi.puppet.com/v3/modules/camptocamp-openldap -d '{"action": "deprecate", "params": {"reason": "This module has been moved to the care of Vox Pupuli where it is now being maintained and updated.", "replacement_slug": "puppet-openldap"}}'
```

**Comment by root-expert** [comment]
The module has been marked as deprecated by camptocamp.
