### ISSUE TITLE
systemd::escape function is does not escape a lot of other characters

### ISSUE THREAD

**Issue by jkroepke** [voxpupuli/puppet-systemd#242]
The function [`systemd::escape`](https://github.com/voxpupuli/puppet-systemd/blob/master/functions/escape.pp) introduced in https://github.com/voxpupuli/puppet-systemd/pull/220 supports only a minimalistic subset of escape sequences.

For mount units, the `-` needs to be escaped and replaced by `\x2d` (hex representation).

In general, numbers, letters and some special chars are [allowed](https://github.com/systemd/systemd/blob/16d41892c36bc31921c112ee6529f2d15a8fd449/src/basic/unit-name.c#L19-L32) and others needs to be [replaced by a hex presentation](https://github.com/systemd/systemd/blob/16d41892c36bc31921c112ee6529f2d15a8fd449/src/basic/unit-name.c#L293-L302).

Before someone ask 'Can you create a PR?'. 

First I want to know if it worth to reimplement the systemd-escape logic into the puppet DSL or should the puppet function replaced by a function it's simply calling `systemd-escape`? In combination with [`Defferred functions`](https://puppet.com/docs/puppet/6/deferring_functions.html), it should NOT add the dependency having systemd installed on the puppet master.

In case the current function should extend, I need to know how I can convert strings/chars to octal or hex decimal and do comparisons like `if "x".ord > 127`?

**Comment by jkroepke** [comment]
> Problems with calling systemd-escape on master is that different versions of systemd do different things so you never quite no what you are getting. Server might even be running windows.

Or running inside kubernetes ...

Thats correct and thats the reason why this functions should be always called [deferred](https://puppet.com/docs/puppet/6/deferring_functions.html). This avoids any dependency against the master since systemd-escape is executed on the agent only.


> Indeed the - is missed from test cases.

And any other special chars, too. Mount points can go wild (looking at samba servers...)

**Comment by traylenator** [comment]
Deferreed is pretty limited - e.g cannot be called in a template.

Hex is handled 
* https://puppet.com/docs/puppet/6/lang_data_number.html#oct-hex-integers
* `sprintf('%X', 10)`

When I wrote function I wrote from the docs - clearly not enough.

**Comment by jkroepke** [comment]
> cannot be called in a template.

It's documented, how you can use Deferred function in epp templates. https://puppet.com/docs/puppet/6/deferring_functions.html#deferring_functions-deferred-function-example

> Hex is handled

I saw this. Converting Hex to String is simple. Can you figure out, how I can convert character to hex?

```
$ puppet apply -e 'notify{"${sprintf("%x", "x")}": }'
Error: Evaluation Error: Error while evaluating a Function Call, invalid value for Integer(): "x" (line: 1, column: 11) on node 
```

**Comment by traylenator** [comment]
Indeed.  Needs an `ord` function in [extlib](https://github.com/voxpupuli/puppet-extlib) ?

**Comment by jkroepke** [comment]
And now, it begins to be complex.....

Also see the note from @bastelfreak  .. https://github.com/voxpupuli/puppet-systemd/pull/243#discussion_r790476832

**Comment by ekohl** [comment]
> Indeed. Needs an `ord` function in [extlib](https://github.com/voxpupuli/puppet-extlib) ?

Why extlib and not stdlib?

**Comment by jkroepke** [comment]
And why not puppet core?

I guess extlib would be the fastest way to get such a function. The lifecycle of puppet or stdlib maybe takes longer... depends on the puppet development team ...
