### ISSUE TITLE
Missing dependency in metadata.json

### ISSUE THREAD

**Issue by tuxmea** [voxpupuli/puppet-systemd#281]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: any
- Ruby: any
- Distribution: any
- Module version: latest

## What are you seeing

oomd uses shellvar resource type from augeasproviders_shellvar
But this is not mentioned in metadata.json

**Comment by ekohl** [comment]
It is a soft dependency that's mentioned here:
https://github.com/voxpupuli/puppet-systemd#machine-info-hostnamectl

Should this also be documented in the `@param` documentation? Sadly this is something that the Puppet ecosystem doesn't really deal well with.

**Comment by tuxmea** [comment]
@ekohl on the other hand we set the apt module usually in metadata.json, which is not needed when not using Debian based systems.
So apt can be considered to be a soft-dependency, too.

Question is now: How should we deal with soft-dependencies in metadata.json?

**Comment by tuxmea** [comment]
Had a chat with @bastelfreak. Soft dependencies should not be listed in metadata.json. Closing issue.

**Comment by ekohl** [comment]
You do raise a valid point about apt. In the majority of cases that can indeed be a soft dependency.
