### ISSUE TITLE
Revisit setting daemon-reload to true by default

### ISSUE THREAD

**Issue by trevor-vaughan** [voxpupuli/puppet-systemd#284]
We need to revisit setting `systemd::daemon_reload` to `true` by default in calls from `unit_file`.

There may be bugs in Puppet and/or other things that this is currently masking.

Relates to #277 

## Notes from IRC

> 16:45 < tvaughan> ewoud: Do you think that `daemon-reload` should simply be implied no matter what? The only reason I added the parameter was to preseve the current (in my opinion broken) state if someone wanted it for whatever reason
> 16:50 < ewoud> tvaughan: I think it's a good question - ideally speaking you manage the service with Puppet and then Puppet 6.1.0+ should take care of the daemon-reload is needed - that said, we did find out that cases where you ensure something is absent, that won't work
> 16:51 < ewoud> also, having a drop in file but not managing the service would break, but I'm not sure why you'd do that (the manual restart in service_limits is still weird and something I'd deprecate)
> 16:52 < tvaughan> At this point, I know that it works with GDM and NFS (the hard edge cases) so I'd like to get it through and then we can figure out if puppet is broken or something else is going on
> 16:52 < ewoud> so I do wonder in which other cases it would be needed
> 16:52 < tvaughan> Both GDM and NFS actually have other auto-spawned items that need to happen in between the file drop and the service
> 16:52 < ewoud> GDM and NFS on which OSes (and versions)?
> 16:52 < tvaughan> So, there's systemd magic going on as well
> 16:52 < tvaughan> EL7 and 8 (and I suspect 9)
> 16:53 < tvaughan> GDM because we're working around `hidepid=2` issues
> 16:53 < tvaughan> Basically, there are more situations that need the intermediate reload than you might think at first glance.
> 16:54 < ewoud> I'm questioning if the default should be true or false - false would mean you don't apply a workaround so technically a bit faster but true catches more issues
> 16:54 < tvaughan> That said, we could disable it by default and have users call it explicitly. That would reduce the execs but leave you scratching your head as to why things aren't working the way you expect
> 16:54 < tvaughan> (and/or puppet itself isn't doing what it's supposed to)
> 16:56 < tvaughan> ewoud: The daemon reload execs are fast and (unless you have a TON of dropins) you're really not going to notice

**Comment by jhoblitt** [comment]
@trevor-vaughan I assume this was resolved by #277? I'm going to close the issue but feel free to reopen it.

**Comment by trevor-vaughan** [comment]
@jhoblitt Yes, thank you. Apparently I type badly :-/
