### ISSUE TITLE
circular dependency when using `systemd::unit_file` and `systemd::dropin_file` for the same service

### ISSUE THREAD

**Issue by simondeziel** [voxpupuli/puppet-systemd#286]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.27.1-1focal
- Distribution: Ubuntu 20.04
- Module version: head of git (commit 673cbc993e61)

## How to reproduce (e.g Puppet code you use)

```puppet
  $content = @(EOF)
  # File managed by Puppet
  [Service]
  ExecStart=/bin/echo first
  | EOF
  systemd::unit_file { 'foo.service':
    content => $content,
  }

  $add_content = @(EOF)
  [Service]
  ExecStartPost=/bin/echo second
  | EOF
  systemd::dropin_file { 'foo-addition.conf':
    unit    => 'foo.service',
    content => $add_content,
    require => Systemd::Unit_file['foo.service'],
  }
```

## What are you seeing

```shell
# puppet agent -t
Info: Using environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Info: Caching catalog for log.int.sdeziel.info
Info: Applying configuration version '1674843695'
Error: Found 1 dependency cycle:
(Exec[systemd-foo.service-systemctl-daemon-reload] => Systemd::Daemon_reload[foo.service] => Systemd::Unit_file[foo.service] => Systemd::Dropin_file[foo-addition.conf] => File[/etc/systemd/system/foo.service.d/foo-addition.conf] => Systemd::Daemon_reload[foo.service] => Exec[systemd-foo.service-systemctl-daemon-reload])\nTry the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
Error: Failed to apply catalog: One or more resource dependency cycles detected in graph
```

## What behaviour did you expect instead

This used to work before commit 2ed469f3097afa1f658f20318de267427478d88d and also with the never merged PR #237

**Comment by traylenator** [comment]
Is there ever a need to have ?

```
require => Systemd::Unit_file['foo.service
```

on the drop file?

May be easier to just avoid the problem rather than fix.

**Comment by jhoblitt** [comment]
The unit and drop in resources do not need to be ordered.  `daemon-reload` and the service will only be restarted once regardless of which order the the unit and drop in(s) are in the catalog.

**Comment by jhoblitt** [comment]
Copying my comment from #300:

_I suspect the only way around this is if systemd::dropin_file would not notify Systemd::Daemon_reload[$unit] or Service <| title == $unit or name == $unit |> and instead notified the related systemd::unit_file._

**Comment by simondeziel** [comment]
@jhoblitt I'm not sure I understand your proposal. Here's what I tried:

```
  $add_content = @(EOF)
  [Service]
  ExecStartPost=/bin/echo second
  | EOF
  systemd::dropin_file { 'foo-addition.conf':
    unit    => 'foo.service',
    content => $add_content,
    notify  => Systemd::Unit_file['foo.service'],
    daemon_reload => false,
  }
```

With the above snippet, puppet will only call the `daemon-reload`, not do the actual service restart:

```
root@log:~# rm /etc/systemd/system/foo.service.d/foo-addition.conf
root@log:~# systemctl daemon-reload
root@log:~# puppet agent -t
Info: Using environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Info: Caching catalog for log.int.sdeziel.info
Info: Applying configuration version '1674843819'
Notice: /Stage[main]/Main/Node[log.int.sdeziel.info]/Systemd::Dropin_file[foo-addition.conf]/File[/etc/systemd/system/foo.service.d/foo-addition.conf]/ensure: defined content as '{md5}ee03cd742c8fbb1b67e55a4799805565' (corrective)
Info: Systemd::Dropin_file[foo-addition.conf]: Scheduling refresh of Systemd::Unit_file[foo.service]
Info: Systemd::Unit_file[foo.service]: Scheduling refresh of Systemd::Daemon_reload[foo.service]
Info: Systemd::Daemon_reload[foo.service]: Scheduling refresh of Exec[systemd-foo.service-systemctl-daemon-reload]
Notice: /Stage[main]/Main/Node[log.int.sdeziel.info]/Systemd::Unit_file[foo.service]/Systemd::Daemon_reload[foo.service]/Exec[systemd-foo.service-systemctl-daemon-reload]: Triggered 'refresh' from 1 event
```

We can see that foo's log never got the "second" echo:

```
root@log:~# systemctl status foo
○ foo.service
     Loaded: loaded (/etc/systemd/system/foo.service; static)
    Drop-In: /etc/systemd/system/foo.service.d
             └─foo-addition.conf
     Active: inactive (dead)

Jan 27 18:17:28 log systemd[1]: Started foo.service.
Jan 27 18:17:28 log echo[1453]: first
Jan 27 18:17:28 log systemd[1]: foo.service: Deactivated successfully.
```

**Comment by simondeziel** [comment]
@ekohl I think you are right and it's another case of me using the tool wrong :/

My initial issue involved a `systemd::timer` creating both a timer and a service. For some (invalid) reason, I had the dropin try to notify the service which is pointless because it is timer activated...

Your suggestion to enable `active`/`enable` is what made me realize my mistake. Thanks and sorry for the false alert!

**Comment by jhoblitt** [comment]
@simondeziel To clarify, my comments were about possible changes to the defined types to make it harder for end users to create dependency loops.

**Comment by neufeind** [comment]
Refering to what ekohl [on Jan 30, 2023](https://github.com/voxpupuli/puppet-systemd/issues/286#issuecomment-1408868383) said ...
I tried to define the unit_file and a dropin_file on that same service. This lead me to a the circular dependency, since both use a daemon_reload with the same "$unit" value, the service name. Or what am I missing here?
