### ISSUE TITLE
Manage /etc/udev/rules.d directory

### ISSUE THREAD

**Issue by bschonec** [voxpupuli/puppet-systemd#291]
Should the /etc/udev/rules.d directory be purged of non-managed files?

**Comment by ekohl** [comment]
It could have an option, but it feels too invasive to me to do so by default. For example, on my Fedora 36 system:
```console
$ ls /etc/udev/rules.d/
70-persistent-ipoib.rules
$ rpm -qf /etc/udev/rules.d/70-persistent-ipoib.rules 
rdma-core-39.0-1.fc36.x86_64
```

Now the particular file doesn't contain anything and you could argue it should be in `/usr/share/doc` as an example, but there may be more.

**Comment by saz** [comment]
Managing yes, but purging by default should be configurable set to `false` by default.

**Comment by jhoblitt** [comment]
I would like to see this feature too but agree is should be `false` by default.

**Comment by TheMeier** [comment]
The only place `/etc/udev/rules.d` is defined is in https://github.com/voxpupuli/puppet-systemd/blob/master/manifests/udev/rule.pp#L28. So there is no global static setting for the directory :/
