### ISSUE TITLE
Systemd::Unit::Service: missing User and Group

### ISSUE THREAD

**Issue by b4ldr** [voxpupuli/puppet-systemd#299]
a per the description we need to support User and Group in Systemd::Unit::Service

**Comment by thiagolinhares** [comment]
Hi @b4ldr do you plan on merging that piece of code you're working soon?
I ask it because I came across this dependency with a project I'm working on.

Also, if you'd need help evaluating and testing, I would love to help.

**Comment by b4ldr** [comment]
@thiagolinhares in on honestly the patch i was working grew out of control i thikn i need to scrap that and confine myself to just this secific bug, however im not sure when ill have the time to do that
