### ISSUE TITLE
Missing WorkingDirectory parameter on Systemd::Unit::Service

### ISSUE THREAD

**Issue by hboetes** [voxpupuli/puppet-systemd#320]
Hi there,

I just tried to generate a systemd file and got the message that `WorkingDirectory=` and `User=` were unknown options for the service section, so I added them in `types/unit/service.pp`, like so:

```puppet
    Optional['WorkingDirectory']          => String,
    Optional['User']                      => String,
```

After things worked fine again. But… am I missing something or are those options really missing. They are documented: https://www.freedesktop.org/software/systemd/man/systemd.exec.html

Thanks!

**Comment by kenyon** [comment]
As said in #288 

> Not every systemd directive has been added but a healthy set has and subsequents can be added as required.

**Comment by smortex** [comment]
:wave: @hboetes 

Please send these changes as a Pull-Request :wink:

**Comment by jhoblitt** [comment]
Related to #321

**Comment by ekohl** [comment]
Closing as duplicate of #299

**Comment by ekohl** [comment]
Actually going to reopen this and scope it down to just `WorkingDirectory`.

**Comment by traylenator** [comment]
WorkingDirectory was added in c785f4fc2803bfaf3bd2ccc67a952a048000cc3c
