### ISSUE TITLE
Feature Request for socket unit files

### ISSUE THREAD

**Issue by mplaats** [voxpupuli/puppet-systemd#348]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.x
- Ruby: 3.x
- Distribution: debian
- Module version: 5.0.0

Im missing a possibility to create socket unit files in the systemd module. As an example:

/etc/systemd/system/pdnsadmin.socket
```ini
[Unit]
Description=PowerDNS-Admin socket

[Socket]
ListenStream=/run/pdnsadmin/socket

[Install]
WantedBy=sockets.target
```

Would be very helpfull if the module would be extended with this.

**Comment by ekohl** [comment]
Looks like `systemd::manage_unit` doesn't have a `socket_entry` property. This can be considered a missing feature.

You should be able to provide it manually though:
```puppet
systemd::unit_file { 'pdnsadmin.socket':
  content => 'TheActualContent',
  enable  => true,
  active  => true,
}
```

**Comment by mplaats** [comment]
Works perfect! For reference the hiera code used to test the new feature.

systemd::manage_unit:
  'pdnsadmin.socket':
    ensure: present
    unit_entry:
      'Description': 'PowerDNS-Admin socket'
    socket_entry:
      'ListenStream': '/run/pdnsadmin/socket'
    install_entry:
      'WantedBy': 'sockets.target'
