### ISSUE TITLE
Add Debian 12 support

### ISSUE THREAD

**Issue by weestack** [voxpupuli/puppet-systemd#360]
Add debian 12 support. Without this change puppet-systemd will
likely fail with the following error:

Evaluation Error: Error while evaluating a Function Call, Class[Systemd]:
expects a value for parameter 'accounting'
Class[Systemd]: expects a value for parameter 'accounting' (file: /etc/puppetlabs/code/environments/feature_bookworm_update/modules/systemd/manifests/dropin_file.pp, line: 36, column: 3)
Tested on debian 12 bookworm.

**Comment by kenyon** [comment]
#357
