### ISSUE TITLE
create systemd::path

### ISSUE THREAD

**Issue by vogelan** [voxpupuli/puppet-systemd#370]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6
- Ruby: 2.1
- Distribution:
- Module version: actual

## How to reproduce (e.g Puppet code you use)
I tried to code  systemd::path in a Puppet Module the same way I use the systemd::timer 

## What are you seeing
Error 500 on SERVER: "Unknown resource type: 'systemd::path'"

## What behaviour did you expect instead

A Support for systemd Path Units would be helpful. An example use case would be the Monitoring of a Kerberos-Keytab for changes. (This is for example the case, when the Password for the Keytab has changed. Then it would be useful to get a new Kerberos-Ticket, because the old is no longer valid).

monitor.path:

[Unit]
Description="Monitor the /etc/krb5.keytab file for changes"
[Path]
PathModified=/etc/krb5.keytab
[Install]
WantedBy=multi-user.target

monitor.service:

[Unit]
Description=Get new Kerberos TGT using the changed Keytab

[Service]
Type=oneshot
ExecStart=/usr/sbin/get_new-ticket.sh

**Comment by ekohl** [comment]
Puppet sometimes gets confused in multiple environments. It helps to run `puppet generate types`. See https://www.puppet.com/docs/puppet/7/man/generate.html as well.

And as a slight note: Puppet 6 is EOL so I'd recommend updating.

**Comment by traylenator** [comment]
Hi,
There is no `systemd::path` type (that I can see)

However `systemd::manage_dropin` can be used as per  this example.

https://github.com/voxpupuli/puppet-systemd/blob/master/REFERENCE.md#genenerate-a-path-unit

**Comment by TheMeier** [comment]
This can be done with `systemd::unit_file` or `systemd::manage_unit`. There is even a custom type `Systemd::Unit::Path`

I think there is nothing to do here, so I will close it. If you object please feel to re-open if you think it is necessary.
