### ISSUE TITLE
add a cron-like systemd::timer interface

### ISSUE THREAD

**Issue by anarcat** [voxpupuli/puppet-systemd#374]
I'm looking at converting my `cron` resources into a `systemd::timer` but the interface to that resources is rather unwieldy. It assumes prior and rather intricate knowledge of the format of systemd unit files and makes the cron resource look extremely intuitive and fun in comparison (which is not a compliment).

I think there's room for "cron-like" timer interface. We're not talking about reinventing the wheel here, probably just a little template will do. An interface such as:

```
define systemd::unit::job(
    $command,
    $user => root,
    $interval => # [...] that is of course the hard part
) {

    systemd::timer { $name:
        # ....
    }
}
```

Wikimedia operations people actually did this in their own `systemd` module which, strangely, is not related to this module but shares a lot of the interfaces, see their [systemd::timer::job resource](https://gerrit.wikimedia.org/r/plugins/gitiles/operations/puppet/+/fd8b59c7f0be1bcd7a4927d5d572986fe8c9cb47/modules/systemd/manifests/timer/job.pp). It does a *lot* more than just create a timer though: it includes things like logging, monitoring and so on, probably not something we want to merge as-is just now. I mostly cite it as an example of how things could be done.

It makes conversions much easier, here's a [patch of one conversion](https://gerrit.wikimedia.org/r/plugins/gitiles/operations/puppet/+/a22f0afa89e641a792cea13475efff256029fb36%5E%21/). I particularly like the `> /dev/null 2>&1` removal, personally. :)

I mostly open this to get feedback, I'm likely going to implement this on our side anyway, but I figured it could be useful for folks here if I send it as a PR instead of just our secret sauce. See [our internal ticket as well](https://gitlab.torproject.org/tpo/tpa/team/-/issues/41303).

**Comment by traylenator** [comment]
@anarcat I think its a good idea. 

Indeed95% of cron jobs are 
*  run X 
* daily, weekly or   every 2 minutes.
* run as user Y
* Maybe some random component.

Maybe this should be an interface in https://github.com/voxpupuli/puppet-cron -probably not.

**Comment by ekohl** [comment]
I did write [systemd::timer](https://github.com/voxpupuli/puppet-systemd/blob/master/manifests/timer.pp) a while back, but what you're suggesting sounds like adding a [systemd::manage_unit](https://github.com/voxpupuli/puppet-systemd/blob/master/manifests/manage_unit.pp) style layer on top. That sounds useful to me.

As reference: this was the original reason I wanted the systemd::timer resource: https://github.com/theforeman/puppet-puppet/blob/master/manifests/agent/service/systemd.pp. As you can see, https://github.com/theforeman/puppet-puppet/blob/b08528470b9a95ba659f308ca2cafc6bec084c37/templates/agent/systemd.puppet-run.timer.erb#L8 isn't really a complete implementation of the cron spec.

Perhaps it makes sense to write a `cron2timer()` function and leave it up to the end user to combine the two?

**Comment by anarcat** [comment]
> Maybe this should be an interface in https://github.com/voxpupuli/puppet-cron -probably not.

i would rather not. i would like to eventually remove that module if we stop using cron altogether, and putting the shim there would make that difficult.

thinking about this more: i think we should have a straight out compatibility shim in there. and yes, systemd doesn't provide the exact same interface, but we can let the user shoot themselves in the foot there, i think.

i would do a `systemd::timer::cron` define that would match the `cron` interface and shove that in a `OnCalendar` thing and call it a day, to be honest. that would sweep a *lot* under the rug (like syntax differences between `OnCalendar` and cron, email notifications and so on), but that's things i expect people would handle during the conversion. we could even have docstrings pointing out those caveats...

**Comment by TheMeier** [comment]
I did create a MR as a proposal. I have been maintaining and using https://github.com/TheMeier/themeier-systemd_cron for years. This is an adaption of this module to fit inside puppet-systemd and make mine obsoletet :smile:
