### ISSUE TITLE
timedatectl support

### ISSUE THREAD

**Issue by jcpunk** [voxpupuli/puppet-systemd#377]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.26.0
- Ruby: from AIO
- Distribution: CentOS Stream 9
- Module version: 6.0.0

## What behaviour did you expect instead

I'm wondering if it would make sense to add the `timedatectl set-timezone` and `timedatectl set-local-rtc` feature set to this module.

## Any additional information you'd like to impart

https://www.freedesktop.org/software/systemd/man/timedatectl.html

**Comment by kenyon** [comment]
I would use it.

**Comment by TheMeier** [comment]
The only sensible use cases would be `set-timezone` and `set-time` though. Setting `set-local-rtc ` to `1` is discouraged. And ntp should be managed with `systemd::timesyncd`
