### ISSUE TITLE
Invalid option `MaxFree` in `cordedump.conf`

### ISSUE THREAD

**Issue by phihos** [voxpupuli/puppet-systemd#398]
The option `MaxFree` does not show up in [the docs](https://www.freedesktop.org/software/systemd/man/latest/coredump.conf.html#MaxUse=). But there is an option `KeepFree`. Is that an old option or is it a bug?

**Comment by kenyon** [comment]
Looks like that's just a bug, I see no evidence of `MaxFree` ever being a systemd option.
