### ISSUE TITLE
manage_unit service_entry Environment can't have multiple values

### ISSUE THREAD

**Issue by XDjackieXD** [voxpupuli/puppet-systemd#404]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 8.3.1
- Ruby: 
- Distribution: Debian Bookworm
- Module version: 6.3.0

## How to reproduce (e.g Puppet code you use)

```
  systemd::manage_unit { 'test.service':
    unit_entry    => {
      'Description' => 'Bla',
    },
    service_entry => {
      'Type'        => 'oneshot',
      'Environment' => [
        "bla=foo",
        "bar=bla",
      ],
      'ExecStart'   => '/usr/bin/true',
    },
    enable        => false,
    active        => false,
  }
```

## What are you seeing

An error during the puppet run (see output log)

## What behaviour did you expect instead

A systemd service that contains multiple "Environment=" lines (Which is valid as per https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#Environment)

## Output log

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Systemd::Manage_unit[test.service]: parameter 'service_entry' entry 'Environment' expects a String value, got Tuple (file: /etc/puppetlabs/code/environments/j_test/modules/profile/manifests/test/test.pp, line: 23) on node xxx
```

**Comment by moritzdietz** [comment]
I too just ran into this issue

**Comment by XDjackieXD** [comment]
I solved it this way:
```
  $env = {
    "bla" => "foo",
    "bar" => "bla",
  }
...
'Environment' => $env.map |$k, $v| { "\"${k}=${v}\"" }.join(" "),
```

not the nicest of all solutions but works and is readable enough.

As the proper solution would be pretty easy to do as far as I can tell I would still like to see this fixed in this repo.
