### ISSUE TITLE
Missing parameters under Service section

### ISSUE THREAD

**Issue by mplaats** [voxpupuli/puppet-systemd#425]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: puppet 7/8
- Ruby: latest
- Distribution: debian 12
- Module version: 6.4.0 / latest

Missing 2 options under [Service]

Can you add the options below to configure under the [Service] section ?

PermissionsStartOnly=True/False
RuntimeDirectoryMode=0775etc

Both are now missing in the module to configure but are available in systemd.

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Systemd::Manage_unit[something.service]:
  parameter 'service_entry' unrecognized key 'PermissionsStartOnly'
  parameter 'service_entry' unrecognized key 'RuntimeDirectoryMode'

**Comment by TheMeier** [comment]
Hmmmm, 
`RuntimeDirectoryMode` is here
https://github.com/voxpupuli/puppet-systemd/blob/v6.4.0/types/unit/service.pp#L104
 are you sure your module is up to date, and all pcore/environment caches are updated?

Will add `PermissionsStartOnly`

**Comment by TheMeier** [comment]
`PermissionsStartOnly` is long deprecated, see
https://github.com/systemd/systemd/blob/main/NEWS#L8384
