### ISSUE TITLE
Setting default_target fails due to deprecated shell_escape function 

### ISSUE THREAD

**Issue by jormaster3k** [voxpupuli/puppet-systemd#479]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 8.7.0
- Ruby: ruby 3.0.2p107
- Distribution: Ubuntu 22.04
- Module version: 7.1.0

## How to reproduce (e.g Puppet code you use)

```
# Set systemd config                                                                                               
class { 'systemd':
   default_target => 'multi-user.target',
}
```

## What are you seeing

> Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, deprecation. shell_escape. This function is deprecated, please use stdlib::shell_escape instead. at [".../ext-modules/systemd/manifests/init.pp", 287]:

## What behaviour did you expect instead

Class applies successfully

## Any additional information you'd like to impart

Need to swap out shell_escape() with stdlib::shell_escape()

**Comment by TheMeier** [comment]
stdlib `deprecation` leads to an error in Puppet 8 by default. As a workaround you can change the `strict` setting (https://www.puppet.com/docs/puppet/8/configuration#strict) in the meantime
