### ISSUE TITLE
Unit file path inconsistency

### ISSUE THREAD

**Issue by litepl** [voxpupuli/puppet-systemd#488]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 8
- Ruby:
- Distribution:
- Module version: 7.1.0

## What are you seeing

Unit file is created in `/etc/systemd/system`

## What behaviour did you expect instead

Unit file is created in `/usr/lib/systemd/system`

## Any additional information you'd like to impart

In line 73 of `manifests/unit_file.pp` the default path is set to `/etc/systemd/system` but README says it should be created in `/usr/lib/systemd/system`

**Comment by kenyon** [comment]
`/etc` is the correct place for unit files created like this. The readme should be corrected.

**Comment by litepl** [comment]
> `/etc` is the correct place for unit files created like this. The readme should be corrected.

Hmm, I can't agree as putting it in /etc prevents using enable => mask for ex.

**Comment by traylenator** [comment]
> > `/etc` is the correct place for unit files created like this. The readme should be corrected.
> 
> Hmm, I can't agree as putting it in /etc prevents using enable => mask for ex.

It's true you can't deploy a custom config and also mask a unit but that's entirely correct that you can't I would say.
A custom config for a masked unit makes no sense.

**Comment by litepl** [comment]
It does. Imagine you have some stages in provisioning:
1. Pre-prod - unit file is created with some data from the template, to be checked before prod. Prevent running manually.
2. Prod - fully running service
The most secure option in 1 is to mask the service. 
Another example, when you have to shutdown the service for some nodes only and you want to prevent incidental run.
